name: Giftwrap

on:
  push:
    tags:
      - '**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v1
        
      - uses: nebularg/actions-luacheck@v1
        with:
          args: "--no-color -q"
          annotate: warning
        
      - run: ./generate_changelog.sh

      - name: Retail
        uses: BigWigsMods/packager@v1

      - name: Burning Crusade
        uses: BigWigsMods/packager@v1
        with:
          args: -g bcc
